language: node_js
node_js:
- 9.3.0
- 9.2.1
- 9.2.0
- 9.1.0
- 9.0.0
- 8.9.3
- 8.9.2
- 8.9.1
- 8.9.0
- 8.8.1
- 8.8.0
- 8.7.0
- 8.6.0
- 8.5.0
- 8.4.0
- 8.3.0
- 8.2.1
- 8.2.0
- 8.1.4
- 8.1.3
- 8.1.2
- 8.1.1
- 8.1.0
- 8.0.0
- 7.10.1
- 7.10.0
- 7.9.0
before_install:
- npm install -g codeclimate-test-reporter
after_success:
- codeclimate-test-reporter < coverage/lcov.info
